### ISSUE TITLE
Floating capes when chestplate is hidden

### ISSUE THREAD

**Issue by Oery** [Trikzon/Armor-Visibility#13]
Capes has an offset to be more visible when wearing a chestplate. This offset remains when hiding the armor, which result into a cape floating in the air

## Expected Behavior
When hiding the armor, the cape offset should be removed.

## Current Behavior
The cape offset stay the same and the cape ends up floating

With hidden armor :
![image](https://user-images.githubusercontent.com/48154940/197793644-ff880f00-8058-4652-aa02-99a472d53e1f.png)

Without armor :
![image](https://user-images.githubusercontent.com/48154940/197793817-23ac4117-b3e1-47a8-ae66-631b79b17784.png)

**Comment by Trikzon** [comment]
Thanks for reporting. Since it's not game-breaking and I don't have tons of time rn, I'll put this off until my next update.

**Comment by Trikzon** [comment]
Should be fixed in the 1.20.2 and later versions.
