### ISSUE TITLE
the armor is still seen by other people in server 1.19.2

### ISSUE THREAD

**Issue by papillo12** [Trikzon/Armor-Visibility#14]
the mod is in the client and the server, in the latest version and it does not work so that other players do not see my armor.
## Expected Behavior

it does not work to hide my armor from other players
## Steps to Reproduce

1.
2.
3.
4.

**Comment by Trikzon** [comment]
This mod is only client side. It's only purpose is for you, the player with the mod installed, to see underneath other players' armor. Other players will still see your armor unless they choose to install the mod and toggle armor visibility themselves.
