### ISSUE TITLE
Any Head is invisible when you wear it

### ISSUE THREAD

**Issue by ChillBrian** [Trikzon/Armor-Visibility#15]
Whenever I put on a player head or mob head my skin layer just disappears and the head is not shown

## Expected Behavior
That I see the head I am wearing

## Current Behavior
The head just disappears and the skin layer too

## Steps to Reproduce
1. Turn on the mod
2. Put a head on your head
3.
4.

## Context (Environment)
This is most noticeable in an SMP I have where player heads are common and they like to wear it.

**Comment by Trikzon** [comment]
Can you post a screenshot of this happening? I am not able to reproduce it. What version are you using?

**Comment by Trikzon** [comment]
Feel free to reopen this issue if you have more information.
