### ISSUE TITLE
Forge 1.20 Crashing on Startup

### ISSUE THREAD

**Issue by Nikkotg** [Trikzon/Armor-Visibility#16]
As the only mod in-folder using forge 1.20, the game crashes on startup after launch with the crash report error:

"org.spongepowered.asm.mixin.throwables.ClassMetadataNotFoundException: com.diontryban.ash.api.options.ModOptionsManager"

The mod options manager seems to me like a reference to the fabric and may be preventing forge from working by looking for something not supposed to be there.

**Comment by Trikzon** [comment]
Do you have Ash API installed? It's a requirement. ModOptionsManager is my own class in my own library that manages the saving and loading of config (or options) files.

You can download Ash API either on CurseForge or on Modrinth:
https://www.curseforge.com/minecraft/mc-mods/ash-api/files/4577126
https://modrinth.com/mod/ash-api/version/2.0.0-rc.2-forge

**Comment by Trikzon** [comment]
It's weird that the game didn't tell you that you were missing a dependency though since it should know that

**Comment by Nikkotg** [comment]
Ah I see, yeah the dependency was well-hidden.
