### ISSUE TITLE
[Feature Request] Add Curios Support

### ISSUE THREAD

**Issue by Camawama** [Trikzon/Armor-Visibility#19]
If at all possible, could you add curios support? Curios has little buttons to enable/disable render of specific slots but it would be nice to hide everything on a person using the same keybind. It might be possible to just tie into Curios and just have the keybind uncheck the checkboxes in curios.

**Comment by Trikzon** [comment]
This sounds like it would be better as a Curios feature (for Curios to add a keybind to their armor hiding toggles)
