### ISSUE TITLE
Add keybind setting

### ISSUE THREAD

**Issue by Glazoed** [Trikzon/Armor-Visibility#20]
Mod isn't usable with PlasmoVoice or other  mods that needs V button, so change button function could be very useful.

**Comment by Trikzon** [comment]
@Glazoed The mod has allowed you to change the button for as long as the mod exists. It's in Minecraft's control settings

![image](https://github.com/Trikzon/armor-visibility/assets/29845000/39729a05-1b4f-468d-8180-26d8a98c8c89)
