### ISSUE TITLE
non-armor head items do not toggle

### ISSUE THREAD

**Issue by ayunami2000** [Trikzon/Armor-Visibility#5]
e.g. stone block on the player's head does not toggle

## Expected Behavior

any item on the player's armor slots would be toggled from visibility

## Current Behavior

only ARMOR is toggled but not blocks. the intention is to toggle what the player is wearing which is not achieved

## Possible Solution

not sure but it shouldnt be too difficult

## Steps to Reproduce

1. e.g. with essentials plugin: hold a non-armor item (e.g. stone) and do /hat
2. toggle off armor
3. notice the non-armor item is still there

## Context (Environment)

trying to toggle full armor **not very important and may remove this mod from my current mod list because it is so minor

1.17. using other mods. namely, multiconnect would be the culprit if not this mod

.

**Comment by Trikzon** [comment]
hmm... this is something I never considered. It may be possible for me to find code where *all* armor is rendered and disable that when armor is toggled off... but I'm not sure if something like that exists. This isn't a huge priority for me to fix, so if it is it will only be in 1.17 and beyond.

**Comment by Tartarus6** [comment]
bump

**Comment by Trikzon** [comment]
Honestly, I don't see this as being necessary. It could even be considered an intended feature that it doesn't hide blocks and non-armor-items.

I will be updating all my mods very soon tho, so I'll look into it.

**Comment by Trikzon** [comment]
In the next update, this should be implemented. It turned out to be easier than I expected
