### ISSUE TITLE
Elytra toggle doesnt work

### ISSUE THREAD

**Issue by MiniJacob64** [Trikzon/Armor-Visibility#8]
When I go into the config file and switch "Keep_elytra_visible" to true. it still toggles the elytra off. This is what the config looks like 
{
  "version": 2,
  "hide_all_armor_toggle": false,
  "hide_my_armor_toggle": false,
  "show_join_message": true,
  "keep_elytra_visible": true
}

Thanks!

**Comment by Trikzon** [comment]
I'll check it out. Thanks for reporting

**Comment by Trikzon** [comment]
Patched in ad942c9. Please wait up to 24 hours for the patch to be uploaded and approved to Modrinth and CurseForge.

Thanks again for reporting this :)

**Comment by MiniJacob64** [comment]
Thank you for fixing it! Fantastic mod :)
